name: Build Android 64-bit LibVNCServer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build LibVNCServer for Android
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Download and set up Android NDK
      - name: Download Android NDK
        run: |
          export NDK_VERSION="25.2.9519653"
          curl -sSL "https://dl.google.com/android/repository/android-ndk-r${NDK_VERSION}-linux.zip" -o android-ndk.zip
          unzip -q android-ndk.zip -d $HOME
          export ANDROID_NDK=$HOME/android-ndk-r${NDK_VERSION}
          echo "ANDROID_NDK=$ANDROID_NDK" >> $GITHUB_ENV

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git autoconf automake libtool pkg-config unzip

      # Step 4: Build LibVNCServer
      - name: Compile LibVNCServer
        run: |
          # Load NDK environment
          source $GITHUB_ENV
          export TOOLCHAIN=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64
          export PATH=$TOOLCHAIN/bin:$PATH
          export TARGET=aarch64-linux-android
          export API=21

          # Clone LibVNCServer (if not already in the repo)
          git clone https://github.com/LibVNC/libvncserver.git
          cd libvncserver

          # Configure the build
          autoreconf -fiv
          ./configure --host=$TARGET --prefix=$(pwd)/build-output \
                      --enable-shared --disable-static \
                      CFLAGS="--sysroot=$TOOLCHAIN/sysroot"

          # Build the library
          make -j$(nproc)

          # Install the library
          make install

      # Step 5: Upload compiled library
      - name: Upload compiled binaries
        uses: actions/upload-artifact@v3
        with:
          name: libvncserver-android-arm64
          path: libvncserver/build-output/
